export const CODE_ABORTED = 'ERR_ABORTED'
export const CODE_TIMEOUT = 'ERR_TIMEOUT'
export const CODE_NETWORK = 'ERR_NETWORK'
export const CODE_NOT_FOUND_HANDLER = 'ERR_NOT_FOUND_HANDLER'
export const CODE_OBSERVE = 'ERR_OBSERVE'
export const CODE_UNSUPPORTED_FIELD_TYPE = 'ERR_UNSUPPORTED_FIELD_TYPE'
export const CODE_INVALID_CLIENT = 'ERR_INVALID_CLIENT'
export const CODE_INVALID_CLIENT_ENDPOINT = 'ERR_INVALID_CLIENT_ENDPOINT'
export const CODE_NOT_FOUND_GLOBAL_CLIENT = 'ERR_NOT_FOUND_GLOBAL_CLIENT'
export const CODE_INVALID_HTTP_CONTEXT_TOKEN = 'ERR_INVALID_HTTP_CONTEXT_TOKEN'
export const CODE_UNKNOWN = 'ERR_UNKNOWN'

export type DefjsErrorCode =
  | typeof CODE_ABORTED
  | typeof CODE_TIMEOUT
  | typeof CODE_NETWORK
  | typeof CODE_NOT_FOUND_HANDLER
  | typeof CODE_OBSERVE
  | typeof CODE_UNSUPPORTED_FIELD_TYPE
  | typeof CODE_INVALID_CLIENT
  | typeof CODE_INVALID_CLIENT_ENDPOINT
  | typeof CODE_NOT_FOUND_GLOBAL_CLIENT
  | typeof CODE_INVALID_HTTP_CONTEXT_TOKEN
  | typeof CODE_UNKNOWN
