import type { executeHttpCommand } from './index.js'
import type {
  AnyStruct,
  BasicAuthInterceptorOptions,
  ClientConfig,
  ClientOptions,
  DefinitionError,
  ErrorMap,
  FlattenedStructError,
  FormattedStructError,
  HttpAwaitResult,
  HttpCommand,
  HttpContext,
  HttpContextToken,
  HttpExecuteOptions,
  HttpInterceptor,
  HttpInterceptorNext,
  HttpProgressEvent,
  HttpProgressFn,
  HttpRequest,
  HttpResponse,
  HttpResponseType,
  HttpStatusError,
  Infer,
  InterceptorFn,
  MakeResponseOptions,
  ObjectStruct,
  ParseResult,
  QueryParamsSerializer,
  RequestCommandBuilder,
  RequestDefinition,
  RequestError,
  RequestErrorData,
  RequestOutputShape,
  RequestStruct,
  RequestSuccessData,
  ResponseGroupItem,
  Struct,
  StructError,
  StructInput,
  StructIssue,
  StructLike,
  StructMethods,
  TransportError,
  UseRequestConfig,
} from './index.js'

export type {
  AnyStruct,
  BasicAuthInterceptorOptions,
  DefinitionError,
  ErrorMap,
  FlattenedStructError,
  FormattedStructError,
  HttpAwaitResult,
  HttpCommand,
  HttpContext,
  HttpContextToken,
  HttpExecuteOptions,
  HttpInterceptor,
  HttpInterceptorNext,
  HttpProgressEvent,
  HttpProgressFn,
  HttpRequest,
  HttpResponse,
  HttpResponseType,
  HttpStatusError,
  Infer,
  InterceptorFn,
  MakeResponseOptions,
  ObjectStruct,
  ParseResult,
  QueryParamsSerializer,
  RequestCommandBuilder,
  RequestDefinition,
  RequestError,
  RequestErrorData,
  RequestOutputShape,
  RequestStruct,
  RequestSuccessData,
  ResponseGroupItem,
  Struct,
  StructInput,
  StructIssue,
  StructLike,
  StructMethods,
  TransportError,
  UseRequestConfig,
}

export type HttpClientOptions = Pick<
  ClientOptions,
  'endpoint' | 'http' | 'interceptors' | 'queryParamsSerializer' | 'xsrf' | 'withCredentials'
>
export type HttpClientConfig = Pick<
  ClientConfig,
  'endpoint' | 'http' | 'interceptors' | 'queryParamsSerializer' | 'xsrf' | 'withCredentials'
>
export type HttpClientOption = (config: HttpClientConfig) => void

export type HttpClient = {
  execute<TInput extends AnyStruct | undefined, TOutput extends RequestOutputShape | undefined>(
    command: HttpCommand<TInput, TOutput>,
    options?: HttpExecuteOptions,
  ): ReturnType<typeof executeHttpCommand<TInput, TOutput>>
}

export {
  ERR_ABORTED,
  ERR_TIMEOUT,
  StructError,
  basicAuthHttpInterceptor,
  createDefinitionError,
  createHttpInterceptor,
  createHttpStatusError,
  createTransportError,
  defineRequest,
  executeHttpCommand,
  fetchHandler,
  isHttpContext,
  isHttpContextToken,
  makeHttpContext,
  makeHttpContextToken,
  makeResponse,
  mergeHttpContexts,
  setErrorMap,
  struct,
  withCredentials,
  withEndpoint,
  withHTTPHandle,
  withInterceptors,
  withQueryParamsSerializer,
  withXSRF,
} from './index.js'

export declare function createHttpClient(...options: HttpClientOption[]): HttpClient
