// DO NOT EDIT.
// Code generated by @defjs/cli v1.34.1
// source: service/iam/iam.proto

import { defineRequest, field } from "@defjs/core";

/**
 * dasdasdsa12312312 */
export const useGetUser = defineRequest<number>("POST", "/v1/cart").withField({
    id: field<number>("10").withJson("uid").withQuery(),
    name: field<string>("").withJson("uid").withQuery()
});

/**
 * dasdasdsa12312312 */
export const useGetUser = defineRequest<number>("POST", "/v1/cart").withField({
    id: field<number>("10").withJson("uid").withQuery(),
    name: field<string>("").withJson("uid").withQuery()
});

/**
 * dasdasdsa12312312 */
export const useGetUser = defineRequest<number>("POST", "/v1/cart").withField({
    id: field<number>("10").withJson("uid").withQuery(),
    name: field<string>("").withJson("uid").withQuery()
});

