name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      any: ${{ steps.filter.outputs.any }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            any:
              - '**'
              - '!**.md'
              - '!docs/**'
              - '!**/*.drawio'
              - '!LICENSE'

  checks:
    needs: changes
    if: ${{ needs.changes.outputs.any == 'true' }}
    uses: ./.github/workflows/_checks.yml
    secrets: inherit

  dependency-review:
    needs: changes
    if: ${{ github.event_name == 'pull_request' && needs.changes.outputs.any == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
